### ISSUE TITLE
Help create a new GW Open Source Conference logo

### ISSUE THREAD

**Issue by david-lippert** [gw-ospo/gw-open-source-stickers#4]
Please help us design our GW Open Source Conference (GW OSCON) logo.  We are hosting a two day conference at GW and we need an event logo that we can be proud of for t-shirts, signs, and everything else.  Please check out the [GW OSPO](https://ospo.gwu.edu/) website for information about the GW open source community to use to inspire your design.  

When you have a design you are happy with, submit a pull request against this issue.  Include a png or svg or a simple markdown file with a link to images that are shareable in box or elsewhere.  Don't hesitate to reach out to ospo@gwu.edu with any questions.  

Thank you!

**Comment by supertwist** [comment]
working on it

**Comment by supertwist** [comment]
detailed responses...

1
Lego is ambiguous re: copyright. on the one hand, this: 
https://www.lego.com/cdn/cs/set/assets/bltaa1b18977a46a9f0/LEGO_SERIOUS_PLAY_Trademark_Guidelines_version_2017.pdf

If we used a photo of an actual Lego brick, then that's a clear violation; the object in my illustration does not [as far as I know] exist - I built it in Rhino [CAD software]. I spent a chunk of yesterday looking for Lego's stance on Open Source in general - there are numerous, well established projects that Lego hasn't made any effort to squash. 

https://ldraw.org/
https://opensource.com/article/20/6/open-source-virtual-lego
https://github.com/ad-si/awesome-lego

Additionally, we're not selling anything for profit.

2
the lego part in the logo - really just meant to convey inbound connection>transformation [direction]>outbound connection...

3
Yes, and I need to spend time refreshing my memory of GitHub - I'll get there, but symptomatic of my limited bandwidth...

4
I stuck to GW colors. I could imagine an illustration with a collection of different mutant legos in Lorena's colors. but for a simple mark that can satisfy lots of different contexts I'd stick to GW colors [or even b/w]

**Comment by supertwist** [comment]
Also - the visual concept attributes you listed for Amyah - super-general - all good things, AND the sky is blue...

When I think about what's specific to OSPO, these SPECIFIC attributes come to mind:

- Plays-nice-with-others [shaing, generosity, altruism, equity]
- Sum-is-greater-than-the-parts [bigger things come from collaboration]
- Impactful [the resources individuals contribute go farther in the world - applies open software, as well as to open learning]

**Comment by supertwist** [comment]
let's see how attachments work...
[OSCON-sketches-02.pdf](https://github.com/user-attachments/files/17802359/OSCON-sketches-02.pdf)

**Comment by supertwist** [comment]
MUTANT LEGOs
![Screenshot 2024-11-18 at 6 59 56 PM](https://github.com/user-attachments/assets/1780d784-68eb-401b-9a2e-6c1ceba151c4)

**Comment by supertwist** [comment]
![B495F895-14E1-42A0-AE91-57F29DD50C75-x](https://github.com/user-attachments/assets/8da2a9c4-9800-4833-a482-6fdacc7b448a)

**Comment by david-lippert** [comment]
Wow.  You really made these.  Supertwist is super cool!

**Comment by david-lippert** [comment]
we concurrently have been working with our GW Marketing team to come up with our GW OSCON logo and I think they did a pretty great job.  Here is a link to the [box folder with the logos](https://gwu.app.box.com/folder/298050520474) we have decided to go with for our first annual GW OSCON.

And here is the main logo for all to see.
![OSCON_horizontal_full-color](https://github.com/user-attachments/assets/98610576-63cd-45f6-b9ce-53e3cfa9691e)
